dist: bionic
sudo: required

before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-add-repository -y ppa:beineri/opt-qt-5.12.0-bionic
    - sudo apt-get -qq update
    - sudo apt-get -qq install g++-4.8 libc6-i386 qt512tools qt512svg qt512webkit qt512serialport qt512multimedia
    - sudo apt-get install libao-dev --yes
    - PATH="/opt/qt512/bin:$PATH"
    - qt512-env.sh

install:
    - wget 'https://s3-us-west-2.amazonaws.com/ucsolarteam.hostedfiles/astyle'
    - tar -zxvf astyle
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf
    - git clone https://github.com/gypified/libmpg123.git
    - (cd libmpg123 && ./configure && make && sudo make install)

script:
    - cd src
    - qmake
    - make
    - "! (astyle *.h *.cpp -r --dry-run --options=astylerc | grep formatted)"

language: cpp
