sudo: required

install:
    - wget 'https://sourceforge.net/projects/astyle/files/astyle/astyle%202.06/astyle_2.06_linux.tar.gz/download'
    - tar -zxvf download
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf

script:
    - "! (astyle *.h *.cpp -r --dry-run --options=astylerc | grep formatted)"

language: cpp
