sudo: required

install:
    - wget 'https://s3-us-west-2.amazonaws.com/ucsolarteam.hostedfiles/astylerc'
    - tar -zxvf astylerc
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf

script:
    - "! (astyle *.h *.cpp -r --dry-run --options=astylerc | grep formatted)"

language: cpp
