#OBJS = files to compile 
OBJS = host.cpp

#CC = compiler used
CC = g++

#COMPLIE_FLAGS = additional flags
COMPILE_FLAGS = -w -g

#LINK_FLAGS
LINK_FLAGS = -lpython2.7

#OUTPUT_NAME = final name
OUTPUT_NAME = test

#INCLUDE FLAGS
INCLUDE_FLAGS = -I/usr/include/python2.7

all : 
	 $(CC) $(OBJS) $(INCLUDE_FLAGS) $(LINK_FLAGS) $(COMPILE_FLAGS)  -o $(OUTPUT_NAME)

